<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SDS200_ControlApp.Domain\SDS200_ControlApp.Domain.csproj" />
    <ProjectReference Include="..\SDS200_ControlApp.Protocol\SDS200_ControlApp.Protocol.csproj" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

</Project>
